let journalEntries = {
  bucika: [
    "When I listen to this song, my thoughts often drift to my grandma.",
    "Honestly, she's not the gentlest person I've known. She's a resilient woman who keeps her vulnerabilities hidden. At times, she can even be a bit fiery.",
    "During my first year away from home, on the night of the Mid-Autumn Festival meant for family reunions, I had a video call with my mother and grandma. As I spoke to them, I noticed my tone turning a bit tearful for some reason. Surprisingly, my grandma picked up on it.",
    '"Don\'t cry," she said. "Be strong when you\'re on your own."',
    "It felt akin to the encouragement in this song that is not quite gentle.",
    '"Hey, stand up!"',
    'The first time I shared this song with a friend who speaks a bit of Wenzhounese (the Wenzhou dialect), she mentioned that "bu ci ka" was what her mother used to say to wake her up in the morning.',
    'Earlier this year, I learned from another friend from Wenzhou that the literal translation of "bu ci ka" is more like "get up" instead of "stand up."',
    `I find that so interesting. It's almost like the way a grandparent would speak to you in a less formal tone - "Hey kiddo, time to get up!"`,
    "I listen to this song when I feel tired, lost, unsure of where I'm headed. It's like my grandma patting me on the back, cheering me up in a less tender but familiar way,",
    `as if she's saying, "There's nothing worth crying about. Just keep moving in that direction. You'll get there eventually."`,
    "My grandma has a tough exterior - a shell that makes her seem resilient. But I know she's warm and soft on the inside. Thinking of her gives me strength.",
    `"Backpack and train tickets / Conflicts in my mind<br><br>What does it taste like? / The world of adults<br><br>Exhilarating, heartbreaking / How many years, how many fleeting moments<br><br>Gaining, losing / In the present, it doesn't matter at all"`,
    `"A down-and-out life / Is this how it ends?<br><br>Don't talk nonsense / Hey, get up<br><br>The sun of tomorrow / From the mountaintop to before your eyes<br><br>The road is under your feet / Don't be afraid / Get up"`,
    `<b><i>"Stand Up"</i></b><br>Shanghai Rainbow Chamber Singers`,
  ],
  german: [
    "A close friend of mine wrote this in their social media profile, and it struck a chord with me.",
    "I find myself pondering this question very often.",
    "For various interconnected reasons, I left the place I once called home.",
    "In the final summer there, I counted down the days until my escape.",
    "I was so eager to break free, as my body and mind had endured too much pain to linger there for even another second.",
    'But can I honestly no longer consider that place "home"?',
    "It's where I grew up and spent almost my entire life.",
    "It's where people who love me reside.",
    "It's the place that, if it weren't my home, wouldn't have caused me so much pain.",
    "I would listen to this song during flights between Shanghai and New York.",
    `The "home" in the song isn't mine. The "foreign land" probably doesn't refer to the place I currently inhabit either.`,
    "Yet, the Cantonese lyrics, even though I only partially understood them, capture all the conflicting emotions I feel.",
    "How I wish that 'home' was truly my home.",
    "How I long to live a life that is 100% mine on the land where my home is.",
    "How much I miss my home.",
    "I prayed for the wind and rain/ To carry me to a distant ideal future<br>For my homeland cannot follow my wishes<br>But why, in the end, after crossing  the sea and coming from afar/ I still yearned to return to my old, worn dwelling at home?",
    "I prayed for the wind and rain/ To carry me back to some place on my homeland<br>The foreign land cannot dispel my exhaustion<br>But why, in the end, upon returning to my home and having barely settled/ I find myself wanting to escape home again?",
  ],
  ruan: [
    "I first heard this song when I was in middle school - it was the outro from an episode of an animation.",
    "I didn’t fully understand the lyrics back then, but with the sound of wave hitting the shore, and the scene where the characters gazing inyo each other’s direction across the coast in silence, I still resonated with the sorrow even as a young kid -",
    "it was a sense of helplessness of people being separated by some vast power beyond their control.",
    "he version I listened to didn’t have any accompaniment, and so the vocal sounded hollow along with the echoes.",
    "It felt like someone was calling the people they were missing from afar when they were alone.",
    "I used to have this stereotype about  Southern Min songs that they always sounded upbeat and optimistic, either because of how words are pronunciated in this dialect or because of the positivity and striving commonly seen in the themes of songs from this culture.",
    "However, the sentimental emotions in this song seemed to be different from the Southern Min songs that I was familiar with -",
    "there was something from deeper within someone’s heart, more tender and intimate. It was a place where I could briefly dwell or linger in for as long as the song lasted.",
    "As I thought of this song again, I had already grown up,",
    "and by growing up, I meant having experienced saying goodbye forever to loved ones, having understood that some damp longings would no longer have an end,",
    "and having uprooted myself from the land where I had lived an entire lifetime to seek and build a desired life in a brand new place.",
    "I wanted to hear you calling my name once more.",
    "I wanted to go back to the time when I was still a little kid.",
    "I wanted feel my hands held tightly by yours once more.",
    "I wanted you to show me how to hold a brush for calligraphy once more. I wanted you to teach me how to make a paper boat once more.",
    "I still remember how you used to walk slowly relying on a silver cane, and I remember you wishing me success when I was about to leave home to study in another country.",
    "I still think of you from time to time, Grandpa. ",
    "Who was that person stayed in my dream<br>One stay is a lifetime<br>I was afraid that when the sun rose<br>And the dream ended<br>We would be separated",
    "Even though we were so far apart<br>I could still tell that<br>It was your silhouette in my dream<br>It was you",
  ],
};
